services:
  chromadb_open:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/data
    restart: unless-stopped
    profiles:
      - chromadb_no_auth

  chromadb_secure:
    image: chromadb/chroma
    expose:
      - "8000"
    volumes:
      - ./chroma-data:/data
    restart: unless-stopped
    profiles:
      - chromadb_token_auth

  proxy_secure:
    image: nginx:alpine
    ports:
      - "8000:8000"
    environment:
      - CHROMA_TOKEN=${CHROMA_TOKEN}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
    depends_on:
      - chromadb_secure
    restart: unless-stopped
    profiles:
      - chromadb_token_auth
