[pytest]

asyncio_mode = auto
pythonpath = .
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

addopts = --junitxml=test_reports/pytest_results.xml